### ISSUE TITLE
Hi sir!

### ISSUE THREAD

**Issue by nromaj** [muggy8/lor-card-maker#1]
**Hello, I greatly respect your work. But now it has some bugs.**

_Now your website is having problems. I cannot enter names, costs, clans, power and healt._

I feel so sad I don't know if you can fix it, but please fix it. I'm longing for my new creations.

Thanks in advance for fixing and thank you for your good works. Hope you have a good day. <3

**Comment by muggy8** [comment]
oh shoot, I didn't realize it's broken since I have been working on other project for so long >_<. I'll see what's wrong and try to push a fix for it over the weekend >_< and maybe stream myself fixing it x'D

**Comment by nromaj** [comment]
Can you tell me? If it's done fixing it.

**Comment by nromaj** [comment]
I have to go to bed haha. It's past midnight now. thank you for your reply I look forward to your work and will continue to support it. good night. <3

**Comment by muggy8** [comment]
haha thanks

**Comment by nromaj** [comment]
Hi Ser!

Can I ask you a question? Have you fixed it already?​

**Comment by muggy8** [comment]
unfortunately, my phone got soft bricked over the weekend and I spent all weekend trying to fix that but I did look into it. I can enter the values just fine but the renderer seem to be broken... can you take a screen recording of how it's broken and what device you're using? thanks

**Comment by nromaj** [comment]
Yes, that's the problem. The display of names, cost, etc. is not working properly.

**Comment by nromaj** [comment]
Do you know what caused it? Because before, it still works normally. Then the next day there was already a problem.

**Comment by muggy8** [comment]
it seems that some of the resources the app needs to run got moved...

**Comment by nromaj** [comment]
Can you fix it?

**Comment by muggy8** [comment]
I just fixed it haha sorry it's been a while... life's been getting in my way >.<
