### ISSUE TITLE
Picture upload bug

### ISSUE THREAD

**Issue by FogoVik** [muggy8/lor-card-maker#11]
When i try to upload a image (jpg or png) this happens:
![image](https://user-images.githubusercontent.com/124563157/216921615-647ed943-b5e5-4c46-ab3c-9b594440af77.png)
![image](https://user-images.githubusercontent.com/124563157/216921770-fdab3e15-d86b-4a31-a96b-74885800be10.png)
![image](https://user-images.githubusercontent.com/124563157/216921880-ddcedef5-021c-415c-9258-914a3eb838b1.png)
![image](https://user-images.githubusercontent.com/124563157/216921960-e6f827ab-dace-40d0-9c6a-94f35b34fa1f.png)

**Comment by muggy8** [comment]
This is what happens when you upload a small image. You can just zoom in.
