### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by ThaoBigby** [muggy8/lor-card-maker#13]
On the browser version, the white text look more bold than the official card text.
Also is it possible to make custom keywords with png imagine and custom text like how you make card?
Thank you, please take your time to respond.
<img width="572" alt="aa" src="https://github.com/muggy8/lor-card-maker/assets/133882846/6c238bac-650c-494a-8026-486ba53cf279">

**Comment by muggy8** [comment]
Oh hmmm I'll take a look at this to see what I can do about the card text. 

Also, you can make keywords with custom PNGs you just have to click the upload image button in the keyword selector and the image editor will show up.

**Comment by muggy8** [comment]
I've made some adjustments to the typography. it should look closer now once you export it n_n
