### ISSUE TITLE
cant use spell building

### ISSUE THREAD

**Issue by Katsura123456789** [muggy8/lor-card-maker#14]
i cant create custom spell option. Everytime i tap it, it just goes blank

**Comment by muggy8** [comment]
what browser are you using?

**Comment by Katsura123456789** [comment]
> what browser are you using?

i used the app from play store.

**Comment by Katsura123456789** [comment]
and thanks for the app btw ;) i liked it, no, i loved it

**Comment by muggy8** [comment]
what device are you using?

**Comment by Katsura123456789** [comment]
> what device are you using?

android 11
vivo 1906

**Comment by muggy8** [comment]
does this happen when you create a new spell or edit an existing spell?

**Comment by Katsura123456789** [comment]
> does this happen when you create a new spell or edit an existing spell?

when i want to create a new spell, i just pressed the spell icon, and then i saw the editing stuff and all but then its just went blank. I waited for it for some time, u know just in case, but nope it wont load or anything, it just blank

**Comment by Katsura123456789** [comment]
> does this happen when you create a new spell or edit an existing spell?

before anything else, maybe i should have told u this first, the spell icon kinda not "lit up"? like the other card icons, does that mean the spell edit still unavailable for the app or?... just curious 😅 if so, then thats ok, i thought its a bug or something... sorry btw😅

**Comment by muggy8** [comment]
Oh geez... this might be an issue... let me check somethin...

**Comment by muggy8** [comment]
spell "icon"? can you take a screen shot/screen recording of what you're seeing?

**Comment by Katsura123456789** [comment]
> spell "icon"? can you take a screen shot/screen recording of what you're seeing?

gimme 1 min

**Comment by Katsura123456789** [comment]
![Uploading Screenshot_20230708_005956.jpg…]()

**Comment by Katsura123456789** [comment]
do u get it?

**Comment by Katsura123456789** [comment]
kinda new with this github btw😅

**Comment by muggy8** [comment]
I can't see it D: maybe try imgur if that's easier or you can always try contacting me on discord (link should be in the app's slide out menu)

**Comment by Katsura123456789** [comment]
owh sorry sorry, i'll try discord
