### ISSUE TITLE
Is it possible to persist cards?

### ISSUE THREAD

**Issue by danbartl** [muggy8/lor-card-maker#2]
Hi, I love your card maker. Is it possible to persist cards so that we can later reference them again? Thanks a lot!

**Comment by muggy8** [comment]
there's a save card button under the card preview. I think that's what you're thinking right?

**Comment by danbartl** [comment]
Hi I'm talking about revisiting older card builds, how would that be
possible? Save seems to only cache the things in browser temporarily?

Muggy Ate ***@***.***> schrieb am Di., 4. Jan. 2022, 5:45 AM:

**Comment by muggy8** [comment]
I'm not sure what you're talking about. you can click on saved cards to re-edit them. yes cards will be saved in the browser cache but I'm not paying for a server so there's nowhere else to store it...

**Comment by danbartl** [comment]
Ok thanks for the clarification!

Am Di., 4. Jan. 2022 um 08:29 Uhr schrieb Muggy Ate <
***@***.***>:
