### ISSUE TITLE
The card editing tools have stopped working

### ISSUE THREAD

**Issue by RedDeath47** [muggy8/lor-card-maker#4]
The zoom in/out and the image editing arrows have all stopped working on mobile pls fix

**Comment by RedDeath47** [comment]
I’m using it on Chrome with my iPhone X. This has been a problem for a little while now.

**Comment by muggy8** [comment]
ouf D: I don't have an iphone of my own to test on (or a mac of my own to debug on ;n;) I'll see what I can do soz ;o;

**Comment by Collector-69** [comment]
I’m also on IPhone and the arrows aren’t moving the image when I put it in.

**Comment by muggy8** [comment]
I'm working on a re-write of the app using React and a potentially more widely supported card drawing method. If all goes well, it should work on iOS safari. I have no idea when it'll be released however :< but should happen before the end of the year

**Comment by muggy8** [comment]
So, I made an update recently. It should probably work on iOS now. No clue if it actually works since I don't have an iPhone. anyways, give it a try.
