### ISSUE TITLE
Hi muggy, I'm not sure if you are still developing LoR Cardmaker but like me and the rest of the Thai community have a few problems. I want you to help me solve it.

The problem is probably because the character's text input fields are too small. Because updating the level up to a separate text other than what it should have. It makes the content-heavy text input greatly reduced. It's really unbalanced. I want you to check and fix it. Everyone is waiting for the day when it gets better.

Thankyou <3

### ISSUE THREAD

**Issue by nromaj** [muggy8/lor-card-maker#5]

**Comment by muggy8** [comment]
sorry I'm not quite understanding what you're suggesting. the level up text is a seperate input from the effect text.

I can de&inately increase the sikt of the input fields though

**Comment by nromaj** [comment]
I will explain again Now, the space for entering character text has been condensed. Because there is a slot for entering text, the level-up condition is added to every card, causing the text effect text to be compressed to become smaller and smaller. Can you increase the space of the normal text input or reduce the area of ​​the text in the level up area to be less or completely excluded?

![Screenshot_20220721_180859.jpg](https://user-images.githubusercontent.com/91742859/180199985-48fa9cf4-a6e2-4c54-92a4-3cf5a54409df.jpg)

The text effect field is too small.

**Comment by muggy8** [comment]
# that's more or less by design... I'll have to think about this one...

**Comment by nromaj** [comment]
Can you fix it T^T

**Comment by muggy8** [comment]
So, thinking about it. what you're asking for would require that each section of the card (name, keywords, effect, and level up text) to all be automatically resized based on the contents of the other sections. While not completely impossible, it would require a complete re-work of how the cards are generated.....

**Comment by nromaj** [comment]
That's how it should be, right? Or is it a mistake?

**Comment by muggy8** [comment]
new version now has this feature n_n
