### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by SaltyOtaku** [muggy8/lor-card-maker#6]
Am I doing something wrong or is there no way to change the text color on the cards? Like I want to have the words strike and attack in yellow like in the game but I'm not seeing a way to do it.

**Comment by muggy8** [comment]
if you scroll down, you'll see the option to add key text (eg strike) and other card mentioned (eg Garen)

**Comment by SaltyOtaku** [comment]
I see it but I don't understand how it works. I tried typing something in those boxes but no words I type in those boxes show up inbthe card when I try to make it.

**Comment by muggy8** [comment]
Make sure the text you type in is the same as the text you want to color in the card effect. for example "Strike" and "strike" are different because of the capital "S" in the first.
