### ISSUE TITLE
Making This to an Android app?

### ISSUE THREAD

**Issue by Yeashamae** [muggy8/lor-card-maker#7]
I like your LoR card maker it's working great and easy to understand Are you planning to make an app version of this? I'll support you by donating if you did.

**Comment by muggy8** [comment]
Currently, I'm working on a complete re-write of the app more industry standard tools and a better solution for rendering and displaying the cards. Additionally, the User Interface (UI) and User Experience (UX) could use some significant upgrades, especially in the art manipulation department. Once that's done, i might consider making an actual android app. That said, if you just want to have a native like experience without the browser related UI, you can always install it as a progressive web app.

PS: yes LoR Card Maker works offline even as it is currently

**Comment by muggy8** [comment]
I've got enough requests for this that I ended up doing it. lol. here you go.

https://play.google.com/store/apps/details?id=com.muggy8.lor_card_maker
