### ISSUE TITLE
Pictures issue

### ISSUE THREAD

**Issue by LuenKayin** [muggy8/lor-card-maker#9]
When I want to export a card a picture from background disappears. What should I do?

**Comment by muggy8** [comment]
what do you mean? I'm not sure i quite understand what you're asking about.

**Comment by LuenKayin** [comment]
> what do you mean? I'm not sure i quite understand what you're asking about.

I added a picture to card but when I want to export it doesn't show 
![Uploading 0bcc6e1a-7644-407c-98d8-9eac39cacea2.png…]()

**Comment by muggy8** [comment]
oh hmm that's odd. what's the image's format? gif? jpg? png?

**Comment by LuenKayin** [comment]
> oh hmm that's odd. what's the image's format? gif? jpg? png?

Its jpg

**Comment by muggy8** [comment]
I found the issue. It's a really dumb optimization issue. If the images are too big, the card's image handler will sometimes fail. I've swapped out some of the inner implementation details so it should work better now,,, in theory...
